theme: jekyll-theme-minimal

port: 4200

language: english

title: Amazon FreeRTOS Workshop

description: Amazon Freertos workshop using the M5 StickC

logo: https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1280px-Amazon_Web_Services_Logo.svg.png

favicon: ./assets/favicon.ico

author: teuteuguy

# destination: ../docs

# show_downloads: true

# run jekyll with: bundle exec jekyll serve